export const REACT_APP_STRIPE_PK = process.env.REACT_APP_STRIPE_PK
export const REACT_APP_API_URL = process.env.REACT_APP_API_URL
export const REACT_APP_IMAGES_HOSTING = process.env.REACT_APP_IMAGES_HOSTING
export const REACT_APP_FACEBOOK_APP_ID = process.env.REACT_APP_FACEBOOK_APP_ID
export const REACT_APP_INSTAGRAM_CLIENT_ID =
  process.env.REACT_APP_INSTAGRAM_CLIENT_ID
export const REACT_APP_EMAIL = process.env.REACT_APP_EMAIL
